version: "3.9"

services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
    env_file:
      - .env
    restart: always
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
