version: "3.9"
services:
  jenkins:
    image: jenkins/jenkins:alpine
    container_name: jenkins
    restart: always
    env_file:
      - ./example.env
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - nginx-proxy

volumes:
  jenkins_data:

networks:
  nginx-proxy:
    name: nginx-proxy
    external: true
